CREATE SCHEMA IF NOT EXISTS part4;
SET SEARCH_PATH TO part4;

DROP TABLE IF EXISTS RaceIn;
DROP TABLE IF EXISTS Racers;
DROP TABLE IF EXISTS ConsistsOf;
DROP TABLE IF EXISTS Stretches;
DROP TABLE IF EXISTS Legs;
DROP TABLE IF EXISTS Cities;
DROP TABLE IF EXISTS Tours;

CREATE TABLE Tours (
    TID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE Cities (
    CID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE Legs (
    LID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    startAt INTEGER REFERENCES Cities(CID),
    endAt INTEGER NOT NULL REFERENCES Cities(CID)
);

CREATE TABLE Stretches (
    name VARCHAR NOT NULL,
    LID INTEGER NOT NULL REFERENCES Legs(LID),
    PRIMARY KEY (name, LID)
);

CREATE TABLE ConsistsOf (
    CID SERIAL PRIMARY KEY,
    TID INT NOT NULL REFERENCES Tours(TID), -- At least one is not supported
    LID INT NOT NULL REFERENCES Legs(LID),
    sequence VARCHAR NOT NULL,
    UNIQUE (TID,LID)
);

CREATE TABLE Racers (
    RID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE RaceIn (
    RID INTEGER NOT NULL REFERENCES Racers(RID),
    CID INTEGER NOT NULL REFERENCES ConsistsOf(CID),
    rank INTEGER NOT NULL,
    PRIMARY KEY (RID,CID)
);

