CREATE SCHEMA IF NOT EXISTS part4;

SET SEARCH_PATH TO part4;

-- Ordered this way as the depend on each other
DROP TABLE IF EXISTS E4;
DROP TABLE IF EXISTS E5;
DROP TABLE IF EXISTS R3;
DROP TABLE IF EXISTS E3;
DROP TABLE IF EXISTS E1;
DROP TABLE IF EXISTS E2;

CREATE TABLE E2 (
    E2ID SERIAL PRIMARY KEY
);

CREATE TABLE E1 (
    E1ID SERIAL PRIMARY KEY,
    E2ID INTEGER NOT NULL REFERENCES E2 -- R1
);

CREATE TABLE E3 (
    E3ID SERIAL PRIMARY KEY,
    E1ID INTEGER NOT NULL REFERENCES E1 -- R4
);

CREATE TABLE R3 (
    E1ID INTEGER NOT NULL REFERENCES E1, -- Interpreted as: REFERENCES R1
    E3ID INTEGER NOT NULL REFERENCES E3 -- Interpreted as : REFERENCES R4
);

CREATE TABLE E5 (
    E5ID SERIAL PRIMARY KEY
);

CREATE TABLE E4 (
    E4ID SERIAL PRIMARY KEY,
    E5ID INTEGER REFERENCES E5 -- R3
);
