CREATE SCHEMA IF NOT EXISTS part4;
SET SEARCH_PATH TO part4;

DROP TABLE IF EXISTS Attends;
DROP TABLE IF EXISTS Lectures;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Tutor;
DROP TABLE IF EXISTS Censors;
DROP TABLE IF EXISTS Teachers;


CREATE TABLE Teachers (
    TID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE Censors (
    CID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE Tutor (
    TuID SERIAL NOT NULL PRIMARY KEY,
    TID INTEGER NOT NULL REFERENCES Teachers(TID),
    CID INTEGER NOT NULL REFERENCES Censors(CID), -- Censor relationship
    fromyear VARCHAR NOT NULL
);

-- Either:
CREATE TABLE Students (
    SID SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    TuID INTEGER NOT NULL REFERENCES Tutor(TuID)
);

-- Or:
-- CREATE TABLE Students (
--     SID SERIAL PRIMARY KEY,
--     name VARCHAR NOT NULL,
--     fromyear VARCHAR NOT NULL,
--     TID INTEGER NOT NULL,
--     CID INTEGER NOT NULL,
--     FOREIGN KEY (TID, CID, fromyear) REFERENCES Tutor(tid, cid, fromyear)
-- );

CREATE TABLE Lectures (
    LID SERIAL PRIMARY KEY,
    subject VARCHAR NOT NULL
);

CREATE TABLE Attends (
    LID INTEGER NOT NULL REFERENCES Lectures(LID),
    SID INTEGER NOT NULL REFERENCES Students(SID),
    PRIMARY KEY (LID, SID)
);